/** @format */
import Header from "@/ui/Header";

export const metadata = {
  title: "My blog website",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
          <body >
        <div className="max-w-[1200px] mx-auto">
          <Header />
          {children}
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
